apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: gogov-kafka
  namespace: default
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 29092
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: '3.8'
    resources:
      requests:
        memory: 512Mi
        cpu: '250m'
      limits:
        memory: 1Gi
        cpu: '500m'
    storage:
      type: persistent-claim
      size: 5Gi # Matches PV size
      deleteClaim: false
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 512Mi
        cpu: '250m'
      limits:
        memory: 1Gi
        cpu: '500m'
    storage:
      type: persistent-claim
      size: 2Gi # Matches PV size
      deleteClaim: false
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
