name: Connect to AWS EKS

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Step 4: Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig --name happy-pop-sparrow --region ${{ secrets.AWS_REGION }}

      # Step 5: Verify connection
      - name: Get Kubernetes Nodes
        run: |
          kubectl get nodes

      # Step 6: Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # Step 7: Deploy Redis
      - name: Deploy Redis
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install my-redis bitnami/redis --set auth.enabled=false

      # Step 8: Verify Redis Deployment
      - name: Verify Redis Deployment
        run: |
          kubectl get pods -l app.kubernetes.io/name=redis
