name: Deploy Strimzi Kafka

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for AWS EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Test Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Install Strimzi CRDs
        run: |
          curl -L "https://strimzi.io/install/latest?namespace=default" -o strimzi-install.yaml
          kubectl apply -f strimzi-install.yaml

      - name: Verify Strimzi Installation
        run: |
          kubectl get crds | grep kafka.strimzi.io

      - name: Deploy Kafka Cluster
        run: |
          kubectl apply -f kafka.yaml --validate=false

      - name: Verify Kafka Deployment
        run: |
          kubectl get kafka gogov-kafka
