name: Deploy Strimzi Kafka

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # - name: Authenticate with Kubernetes
      #   run: |
      #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
      #     export KUBECONFIG=$(pwd)/kubeconfig.yaml
      #     kubectl config view

      # - name: Authenticate with Kubernetes
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
      #   run: |
      #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
      #     export KUBECONFIG=kubeconfig.yaml

      - name: Test Kubernetes Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Check Context
        run: kubectl config current-context

      - name: List All Contexts
        run: kubectl config get-contexts

      - name: Create Kafka Cluster
        run: |
          kubectl apply -f kafka.yaml --validate=false

      - name: Verify Kafka Deployment
        run: |
          kubectl get kafka gogov-kafka
